# Generated by Django 4.2.21 on 2025-05-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryPoint', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerAndKeywords',
        ),
    ]
