# Generated by Django 4.2.21 on 2025-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryPoint', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerandkeywords',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
